package com.nokia.charts.util;

import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.itextpdf.io.codec.Base64;
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.color.Color;
import com.itextpdf.kernel.color.DeviceRgb;
import com.itextpdf.kernel.events.Event;
import com.itextpdf.kernel.events.IEventHandler;
import com.itextpdf.kernel.events.PdfDocumentEvent;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.action.PdfAction;
import com.itextpdf.kernel.pdf.canvas.PdfCanvas;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.border.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Link;
import com.itextpdf.layout.element.ListItem;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.ListNumberingType;
import com.itextpdf.layout.property.TextAlignment;
import com.nokia.charts.entity.testing.FunctionalFailLog;
import com.nokia.charts.entity.testing.FunctionalModule;
import com.nokia.charts.entity.testing.FunctionalSummary;
import com.nokia.charts.entity.testing.Performance;
import com.nokia.charts.entity.testing.PerformanceBaseLine;
import com.nokia.charts.entity.testing.PerformanceExport;

public class PDFUtils {

//	public static final String DEST = "C:/Users/xigao/Desktop/center_text.pdf";
//	public static final String DEST = "C:/Users/Administrator/Desktop/Test.pdf";
	public static final String DEST = "D:/userdata/jiashi/Desktop/Test.pdf";
	public static final String SERVER = "http://135.251.46.16:8080";
	
	public static final Color TITTLE_BG = new DeviceRgb(53,80,100);
	public static final Color HEADER_BG = new DeviceRgb(207, 230, 242);
	public static final Color TEXT_BG = new DeviceRgb(0, 102, 102);
	

	private static final String APPROACH_TEXT = "Using JMeter to simulate users’ requests and get response data to aggregate report.\n Server pressures will be generated by Jmeter to monitor system performance.";
	private static final String SCOPE_TEXT = "1300 users login and take actions within 1 hour.\n 20% of total 1300 login users will take actions (50% Edit, 30% Create, 20% search).";
	private static final String SCENARIO_TEXT = "1300 users Login, 20% users will take actions (50% Edit, 30% Create, 20% search) after login within 1 hour.\n";
	private static final String SCENARIO_TEXT1 = "Duration: 1 hour\n Maximum running users: 1300";
	
	/**
	 * 
	 * @param os OutputStream
	 * @param fileName Generate file name
	 * @param resultTable Data Results
	 * @throws IOException
	 */
	@SuppressWarnings("unchecked")
	public void createPdf(OutputStream os, String fileName, Map<String, Object> resultTable) throws IOException {
		List<FunctionalSummary> summaryList = (List<FunctionalSummary>) resultTable.get("summaryList");
		List<FunctionalModule> moduleList = (List<FunctionalModule>) resultTable.get("moduleList");
		List<FunctionalFailLog> faillogList = (List<FunctionalFailLog>) resultTable.get("faillogList");
		String picBase64Info = (String)resultTable.get("picBase64Info");
		picBase64Info = picBase64Info.replaceAll(" ", "+");
	
		PdfFont HELVETICA = PdfFontFactory.createFont(FontConstants.HELVETICA);
		
		PdfDocument pdf = new PdfDocument(new PdfWriter(os));
		Document document = new Document(pdf,PageSize.A4);
		document.setMargins(10f, 0, 10f, 10f);
		document.add(new Paragraph("Function Testing Report").setTextAlignment(TextAlignment.CENTER).setFont(PdfFontFactory.createFont(FontConstants.TIMES_BOLDITALIC)).setFontSize(14f));
		document.add(new Paragraph(fileName.concat(" Functional Testing Result")).setUnderline().setTextAlignment(TextAlignment.CENTER).setFontSize(10f));
		document.add(new Paragraph("Summary Report:").setFont(HELVETICA).setFontSize(8f));
		document.add(createSummaryReportTable(summaryList));
		document.add(new Paragraph("Module Detail Report:").setFont(HELVETICA).setFontSize(8f));
		document.add(createModuleReportTable(moduleList));
		document.add(new Paragraph("Detail Failed Information:").setFont(HELVETICA).setFontSize(8f));
		document.add(createDetailFailedReportTable(faillogList));
		document.add(new Paragraph("Module Fail/Error/Skip Case:").setFont(HELVETICA).setFontSize(8f));
		document.add(convImage(picBase64Info).setWidthPercent(90f));
		document.close();
	}

	@SuppressWarnings("unchecked")
	private void testIMG(String fileName, Map<String, Object> resultTable) throws IOException{
		List<FunctionalSummary> summaryList = (List<FunctionalSummary>) resultTable.get("summaryList");
		List<FunctionalModule> moduleList = (List<FunctionalModule>) resultTable.get("moduleList");
		List<FunctionalFailLog> faillogList = (List<FunctionalFailLog>) resultTable.get("faillogList");
		String picBase64Info = (String)resultTable.get("picBase64Info");
		picBase64Info = picBase64Info.replaceAll(" ", "+");
		PdfDocument pdfDoc = new PdfDocument(new PdfWriter(DEST));
		Document document = new Document(pdfDoc,PageSize.A4);
		document.setMargins(10f, 0, 10f, 10f);

		PdfFont HELVETICA = PdfFontFactory.createFont(FontConstants.HELVETICA);
		document.add(new Paragraph(fileName.concat(" Functional Testing Result")).setUnderline().setTextAlignment(TextAlignment.CENTER).setFontSize(10f));
		document.add(new Paragraph("Summary Report:").setFont(HELVETICA).setFontSize(8f));
		document.add(createSummaryReportTable(summaryList));
		document.add(new Paragraph("Module Detail Report:").setFont(HELVETICA).setFontSize(8f));
		document.add(createModuleReportTable(moduleList));
		document.add(new Paragraph("Detail Failed Information:").setFont(HELVETICA).setFontSize(8f));
		document.add(createDetailFailedReportTable(faillogList));
		document.add(new Paragraph("Module Fail/Error/Skip Case:").setFont(HELVETICA).setFontSize(8f));
		document.add(convImage(picBase64Info).setWidthPercent(90f));
		document.close();
		
	}
	
	private void justTest(Map<String, Object> resultTable)throws IOException{
		List<FunctionalSummary> summaryList = (List<FunctionalSummary>) resultTable.get("summaryList");
		List<FunctionalModule> moduleList = (List<FunctionalModule>) resultTable.get("moduleList");
		List<FunctionalFailLog> faillogList = (List<FunctionalFailLog>) resultTable.get("faillogList");
		String picBase64Info = (String)resultTable.get("picBase64Info");
		picBase64Info = picBase64Info.replaceAll(" ", "+");
		PdfDocument pdfDoc = new PdfDocument(new PdfWriter(DEST));
		Document document = new Document(pdfDoc,PageSize.A4);
		document.setMargins(10f, 0, 10f, 10f);

		PdfFont HELVETICA = PdfFontFactory.createFont(FontConstants.HELVETICA);
		

		Table table = new Table(1);
		table.setMargins(2, 0, 14, 10).setWidthPercent(90).setFontSize(40f);
		table.setBorder(Border.NO_BORDER);
			    
		String str5 = "CORP JIRA INT";
		String str6 = "Performance Test Report";
		String str10 = "Reporter: Shi";
		String str11 = "Reporter Time: 2017/10/1";
		
	    table.addCell(new Cell().add("1").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("2").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("3").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("4").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str5).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str6).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("7").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("8").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("9").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str10).setFontSize(20f).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str11).setFontSize(20f).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("12").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("13").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("14").setFontSize(10f).setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));

	    document.add(table);
	       
	    
		document.add(new Paragraph("Function Testing Report").setTextAlignment(TextAlignment.CENTER).setFont(PdfFontFactory.createFont(FontConstants.TIMES_BOLDITALIC)).setFontSize(14f));
		document.add(new Paragraph("Summary Report:").setFont(HELVETICA).setFontSize(8f));
		document.add(createSummaryReportTable(summaryList));
		document.add(new Paragraph("Module Detail Report:").setFont(HELVETICA).setFontSize(8f));
		document.add(createModuleReportTable(moduleList));
		document.add(new Paragraph("Detail Failed Information:").setFont(HELVETICA).setFontSize(8f));
		document.add(createDetailFailedReportTable(faillogList));
		document.add(new Paragraph("Module Fail/Error/Skip Case:").setFont(HELVETICA).setFontSize(8f));
		document.add(convImage(picBase64Info).setWidthPercent(90f));
		document.close();
	}
	
	
	public static void main(String[] args) {
		File file = new File(DEST);
		file.getParentFile().mkdirs();
		String picBase64Info = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA/YAAAD6CAYAAAALMtyyAAAgAElEQVR4Xu3df6wlZ33f8e8zCw7ZKAlIJqWVkIOsOrX4I/jOXqwqVfeuLLV1cShEIsUL1Ls2e5dWRcbKSmsllXHIj3pTB9viD7zXv9ZKWNOYCgdtcFMJ7d1KKDL3nourBllaycJW1KqAKZQo2xa881TP8czpc+bOnHnOOXPOfJ8575UQ671zZp55fefMnc88zzxjhD8IIIAAAggggAACCCCAAAIIIBCtgIm25TQcAQQQQAABBBBAAAEEEEAAAQSEYM9BgAACCCCAAAIIIIAAAggggEDEAgT7iItH0xFAAAEEEEAAAQQQQAABBBAg2HMMIIAAAggggAACCCCAAAIIIBCxAME+4uLRdAQQQAABBBBAAAEEEEAAAQQI9hwDCCCAAAIIIIAAAggggAACCEQsQLCPuHg0HQEEEFhlgTRNrxWRCyJyc5IkGzs7O5dCPPzPGWPu2t3dfTLkc4tYZm1t7UZjzPMicp3bhyzLvlXsU9dtW8T+hq4zTdMHROS0iJwXkRODweBK+bMhy4Ruj+UQQAABBBDQIHDs2LG3XnPNNd/e2tp627TtIdhPK8byCCCAAAJjAl7Acv/+gojcNhgMXvMXOnTo0J3W2ifyf6tcZlrWroO9H8rLbQ+90TBtsE/T9KCIPCYiR/MbATvFf1f4nRkMBvdO69r28l6d3mGtvXVvb++lOrvCLSS0hywz7b74x5T/2VW+yTKtIcsjgAACCMwuQLCf3Y5PIoAAAgjMKVAK9lIOQX4YJdhPxm4aTbC+vn44y7Ltoic7X9sw6GsN9t5NneGNhtJNnrFmTxPs5zxs9328fBwT7NsWZn0IIIAAAk0CBPsmIX6OAAIIILAwgSIQGWP+o7X2n5SHT3u9s98Rkb8lIv+jqld/2gYq6rGXoid62n0oL98U7D3r4SME/k0Tjb3KDSMMxobZu5sWzsM9UrGI3vhJtSndbNjXLmvt9V0+sjHvccXnEUAAAQTiECDYx1EnWokAAgj0UsALYZ8XkX/qdtIPut7Pz+TPTY8Nxa/o0Xer2PdsdcXw7V8Xkd/wn7H3t1UMQ/d6uYfbzYswfDbfD8MV7Xh1UmD32lMb7Kt6p/1tTjMU31t2dGMkJNiXQrIzeEREzhhjLuePR7h/+0MR+RPf3XMbHbf+IwalehS1GA23dx9qGmFQ98hCOdiLiHsEYViz4nEPETnlP4dvrb2uNF/BrfnPK4+nYqdKw+9rn+l3y9c8QjD2marh/KXjbDQ3RN6GVh5N6eXJhZ1CAAEEVkyAYL9iBWd3EUAAAU0CXgi7Ow9eR4sg44Uc1+QiPI6CTN0zzeXAUxUyfYOKIdyj58tDgv2EdtSG+5BgXze8u2jvNMG+PKTd7X/NTZEhTYWJT+YHe//fhyHVGPNhb06EscOtqG1NyB3zKo8wcCuqGYpfDsdjk+eJyH3lm0Ll8O8H+5rvR+WcA/6x1TQ3woTjcLjupmf0J8zLQLjXdFKjLQgggMASBD7xiU+4SXO/sbW1NZogdlKw39zc/EdbW1v/qa5pTJ63hKKxCQQQQKDPAn54M8a87D8DniTJev7fZ5IkeT7/ux/siwA3CoSlcOR6+T/jTRA3+qwfEFsI9vtmYa8K0n4dZwlp5XWGBvuqCehmCfZ+cPX96kYRuJ79YuSDt/ywVm77RQ95wwiLfY9e1ARk/xgY1cMY8wVr7Z+JSOVNg2LbpWA/ard3A6AyPHttmThCo+o7XB5FkSTJu8vHePG50k2Yfe3T+ChFn89b7BsCCCDQtcDm5ubvicj7kiR536OPPvrfXHvqgv3m5qYbVXdARD7m3wjw94Fg33VF2T4CCCAQuYAf7K21X/FfQZdl2XA4tAuUbjf90CMi7g51MfHbWG+q3xubJMm9WZY9WzF0ft/r7mYZim+t/eKEmeVdsyuHZ4cE+6Ye3tBg762n7DSaJd8P4f4hVfe8uhfUxwJvXdAtt/Xq1avf9Ye+l183WKx/UmCt6OEuer6LYP+NfF6G4esA/W1M6LEfezSiaWTFND32E0Z2DA2ttW/3bnYMy1AxesU9TlD1R8VbDCI/HdF8BBBAICqBkydPnrbWfiJJkl999NFH/7Ic7I8fP/72a6655svW2he3trb+9aSdI9hHVXoaiwACCOgTqJjQze/9vl5EXnbDu73e++JZ994E+6oh3OXny9272GfpsS9PQFcKtyqDfd0Ig6qjt9STPbyJ4g29f1VE3KSL7y3fuAgN9k098qUbNLXhuuG1ff68B+Vn6N1uu5EnD3rzBBDs9Z3KaBECCCDQicCJEyf+lTHmd7Is+8Drr7/+X4v32J88efKXrbXPuc6Hra2t329qHMG+SYifI4AAAghMFCgH+3IvddFjWX7W3b3rvmqYdHlm+FKP+qj3vGEoftXNg9rJ86p6+pvKXu7Bruuxrnk13TBAhvTYe8t83YVed4OgaFvd8G6/7dP22Ptt8nvbyz38fu90+cZGwwgD97z8g67+rp3lRy/yZ9VHN4eyLHsoSZIviYibHG/4NoD8c2OPT1QNxS/51D7HXpoLYSzcu31xs+JnWfYXeW/8aERA3aiHwt/7uTtu3RwUbuLC0RwUTccYP0cAAQQQWA2BkydPftRa+5S19mPGmM9nWfaRJEmey7LsXz7++ONPhCgQ7EOUWAYBBBBAoFZg0ivY/Oeiq4L9hOHsbnuVz9NXNaQIljWz0Bev4asN9hPaETJ53r5h4q6NVcPwvVcCBgf7qgnoaoJ9mabc+z32SMGkUBryTve6GxtTjDDYV8q699h7k/lVPofvbng0TZ435SMBY21zn/UfM/F+WDwqMOyx956xL+/bsN4THs1g8jzOsQgggMCKCXz84x/feP311188d+7cD92unzhx4v3GGPd4oHuW/kfukfutrS03x4z72XustW99/PHHt+uYCPYrdgCxuwgggEDbAg0zn4/CZFWwd20Jfd1dKbS/kCTJ6SzLnnY9uX6Pcbn3tTxpX77/Va+7qxpCXRu4mnrs830repWHz1q7f8tnmw8K9l6YdB+9rejlXnSwr7sxUfe6u5p/3zfCwK23Zlb88isQy7Piu48W8zEMw70x5o66192JyOhViO6DoRPT1bRtdDOhFMzPe6MJJgX7sREAIa/Ma/s7yvoQQAABBPQJbG5u/uDHP/7xu4pg71p48uTJX7XWPmuM+Qdnz57dLVrtgr0x5qmtra2bCPb6akmLEEAAAQQQmCjQNDO/Rr5JIwwW2d6QGy2L3D7rRgABBBBAYBqBqmBf93mC/TSyLIsAAggggIAigWkmoNPS7PLr38ojDBbZToL9InVZNwIIIIBA2wKbm5s/yrLsfcaYv25ad5Ikv2St/e2tra2/V7csQ/GbFPk5AggggAACCKgXINirLxENRAABBBDwBDY3N78vIu799VebYIwxP22tPbC1tfV3CfZNWvwcAQQQQAABBKIVINhHWzoajgACCCDQggA99i0gsgoEEEAAAQQQQAABBBBAAAEEuhIg2Hclz3YRQAABBBBAAAEEEEAAAQQQaEGAYN8CIqtAAAEEEOhGwIq82Yj8pJutL3+r1ro3t4ld/paXu0VrrTHG9H4/l6vK1hBAAAEE+ixAsO9zddk3BBBAoKcCVuQ9InJWRN47xS5+T0QeMCKfneIzExd1r3Yzxlze3d190v976PrtJTkrVo6JyDWhnxGRL5kN+dAUy3e+6Pnz5/9IRD46ZUP++OjRox+b8jOSvyLwhsFgcK//2fwtA09ba0/t7e29NO16WR4BBBBAAAHNAgR7zdWhbQgggAAClQJW5D+IyK/NyPMOI/Kd8me9d8YXP3rVWnvrpBA4T7C3l+TXxA73Y/o/Vu4xR+Th8gfX19cPZ1m27f97kiQbOzs7l6bfSDufOH/+/HEReXKWtRljjt9+++3nqj5bqtd5ETkxGAyuEOxnkeYzCCCAAAKxCxDsY68g7UcAAQRWUMCKfFPe6LWf5U9qRPZqgv2+nt7QDUzbY28vyqfEyEOh6x9bzsjD5rDcUxPsN4uQO9O6W/7QM88882lr7f2zrNa9s/cjH/nIvs/m4f2WYj/dDQ23fncDoy7Yz7J9PoMAAggggEAsAgT7WCpFOxFAAAEERgJzBvubjMiLBPvlHFBf+MIX7jfGfHqWrdUFe3cTJUmS56tGIhDsZ5HmMwgggAACsQsQ7GOvIO1HAAEEVlBg2cHeBUkROZ1Tnyme355rKP6Se+xdW621PzLGvF9EXjbGPGit/V1r7deNMb9XDNkv7evocYTiGXUR+XMRecQYc5ebW6Dp8FtEsC/32Ptt8IO99277L4rIgyIyesY+38//LiI3i8hRt46uH1tosuTnCCCAAAII1AkQ7Dk2EEAAAQSiE1hgsH/Cw3hBRG5LkuTd7t9c73B5Ajalwd5/xt4P5u7mxIbbp8Fg8FoReo0xnykCeh52pbhxkT+zf8Z9Jne5ICLb5YnpJh1Aiwj2aZoeFJHHXCAv32Aogn0e5C8kSXK6rnYi8uFiHoXc45y19hiT60V3SqDBCCCAwMoLEOxX/hAAAAEEEIhPYIHBvvIZe6/n9zq/Z1dpsK98xr48B0C+T64X+w4X9KtmjS8CdJIkW1mWfcvv8Q49ahYR7Itt5212NxveUQR0rzf/+iLUu+Un3ZTx1lc7xD90f1kOAQQQQACBLgQI9l2os00EEEAAgbkElhXsvZ5h194TeaMfc0E37wWe+XV3y548r6tgv4jJ88oHjz/8Pv/7fSLyHWPMWW80wrXlofjFqwrz4D8cBVDUdq4DlA8jgAACCCCwZAGC/ZLB2RwCCCCAwPwCC3zd3ViPfdEjXPT8Fq+T859Hn/U99gt83d1MPfZ5uHXD9ScNxZ/6PfBtv+4uv9ni5gf4XDFkviLY3yAin3FB3RjzNRfuq3rs/UcT/McO3AiG+Y9S1oAAAggggMDyBAj2y7NmSwgggAACLQnYN151d1ZE3jvFKr8nIg8Ykc9WfaZuNvXS+9I/LyI/30aPvWuD3ZYtNxReRK6ZYj++ZDbkQ1XLV73HvngGvanHPg/2o2fX8/UP5xmoG6of2ubz58//kYh8NHT5fLk/Pnr06MeqPuMNwXcT37k/le+x95aTAwcO/IurV68+ZK095W4IlCYTdOsZzUcwZTtZHAEEEEAAgc4FCPadl4AGIIAAAgjMKmBF3mxEfjLr52P7nLVijBEbW7unba+11hhjFrqf5Rsd07aR5RFAAAEEENAkQLDXVA3aggACCCCAAAJLESDYL4WZjSCAAAIILEmAYL8kaDaDAAIIIIAAAnoECPZ6akFLEEAAAQTmFyDYz2/IGhBAAAEEEEAAAQQQQAABBBDoTIBg3xk9G0YAAQQQQAABBBBAAAEEEEBgfgGC/fyGrAEBBBBAAAEEEEAAAQQQQACBzgQI9p3Rs2EEEEAAAQQQQAABBBBAAAEE5hcg2M9vyBoQQAABBBBAAAEEEEAAAQQQ6EyAYN8ZPRtGAAEEEEAAAQQQQAABBBBAYH4Bgv38hqwBAQQQQAABBBBAAAEEEEAAgc4ECPad0bNhBBBAAAEEEEAAAQQQQAABBOYXINjPb8gaEEAAAQQQQAABBBBAAAEEEOhMgGDfGT0bRgABBBBAAAEEEEAAAQQQQGB+AYL9/IasAQEEEEAAAQQQQAABBBBAAIHOBAj2ndGzYQQQQAABBBBAAAEEEEAAAQTmFyDYz2/IGhBAAAEEEEAAAQQQQAABBBDoTIBg3xk9G0YAAQQQQAABBBBAAAEEEEBgfgGC/fyGrAEBBBBAAAEEEEAAAQQQQACBzgQI9p3Rs2EEEEAAAQQQQAABBBBAAAEE5hcg2M9vyBoQQAABBBBAAAEEEEAAAQQQ6EyAYD8nfZqmB0XkMRE5mq/qzGAwuNf9fX19/XCWZdveJl611t66t7f30pyb5eMIIIAAAggggAACCCCAAAIIDAUI9nMeCGtra78pIl92Yb0I+caYr+3u7j6ZB/tNETkxGAyuzLkpPo4AAggggAACCCCAAAIIIIDAPgGCfcsHxaFDh+50qyTYtwzL6hBAAAEEEEAAAQQQQAABBCoFCPYtHxhpmj6QJMnzOzs7l8pD8ZMk2XD/3rTJtbW1+6+//vrfefbZZ682LcvPEUAAAQQQQAABBBBAAAEEVluAYN9i/ScNvV9bW7vRGHPOWnvMf8Y+TdOnRORYuRlnz55tsWWsCgEEEEAAAQQQQAABBBCYX8BlmjRNj8+/JtbQpgDBviXNPNSfEZHbBoPBa1Wrdb35xpjLbpj+pM2maWoHgwG1aak2rAYBBBBAAAEEEEAAAQQQ6LMA4bGF6oaEercZgn0L2KwCAQQQQAABBBBAAAEEEEBgTIBgP+cB4SbLs9beUjXzfZqmnxSRZ1wPft1Q/KrN02M/Z1H4OAIIIIAAAggggAACCCCwQgIE+zmKnabptSJyQURu9ldjjLnLDbcv/Tz4HfYE+zmKwkcRQAABBBBAAAEEEEAAgRUTINgrLDjBXmFRaBICCCCAAAIIIIAAAgggoFSAYK+wMAR7hUWhSQgggAACCCCAAAIIIICAUgGCvcLCEOwVFoUmIYAAAggggAACCCCAAAJKBQj2CgtDsFdYFJqEAAIIIIAAAggggAACCCgVINgrLAzBXmFRaBICCCCAAAIIIIAAAgggoFSAYK+wMAR7hUWhSQgggAACCCCAAAIIIICAUgGCvcLCEOwVFoUmIYAAAggggAACCCCAAAJKBQj2CgtDsFdYFJqEAAIIIIAAAggggAACCCgVINgrLAzBXmFRaBICCCCAAAIIIIAAAgggoFSAYK+wMAR7hUWhSQgggAACCCCAAAIIIICAUgGCvcLCEOwVFoUmIYAAAgioELAX5VhTQ8wROde0DD9HAAEEEECgTwIEe4XVJNgrLApNQgABBBBQIWC35Zsi8p7axlg5TrBXUSoagQACCCCwRAGC/RKxQzdFsA+VYjkEEEAAgVUTINivWsXZXwQQQACBEAGCfYjSkpch2C8ZnM0hgAACCEQjQLCPplQ0FAEEEEBgiQIE+yVih26KYB8qxXIIIIAAAqsmQLBftYqzvwgggAACIQIE+xClJS9DsF8yOJtDAAEEEIhGgGAfTaloKAIIIIDAEgUI9kvEDt0UwT5UiuUQQAABBFZNgGC/ahVnfxFAAAEEQgQI9iFKE5ZJ0/SgiDwmIkfzxc4MBoN7i4+kafqAiJx2/22MuWt3d/fJpk0S7JuE+DkCCCCAwKoKEOxXtfLsNwIIIIDAJAGC/ZzHx9ra2m+KyJf39vZeKkK+MeZrLsAfOnToTmvtLSJyQkTcDYALSZKc3tnZuTRpswT7OYvCxxFAAAEEeitAsO9tadkxBBBAAIE5BAj2c+BVfdSFeffv1tovup78JEm2iiCfB/0b/B79qnUQ7FsuCqtDAAEEEOiNAMG+N6VkRxBAAAEEWhQg2LeI6Vblht4nSfJ8lmXfEpFHROTuwWDwmvvZ+vr64SzLNl0P/mAwuFK3aYJ9y0VhdQgggAACvREg2PemlOwIAggggECLAgT7FjH94G6tvc4Y86CI3DEp2Kdp+pSIHCs34+zZsy22jFUhgAACCCDQD4EbrxyVg9nl2p155S33y/ffdFs/dpa9QAABBBQKGGPOpWl6XGHTVrpJBPuWyp+H+jMicpsL8mmaXkuPfUu4rAYBBBBAAIFcgB57DgUEEEAAAQT2CxDsWzgqyqHerTIP9k9ba0+5ifXcv/GMfQvYrAIBBBBAYKUFCPYrXX52HgEEEECgRoBgP+eh4c98X35u3g/yVUG/btM8Yz9nUfg4AggggEBvBQj2vS0tO4YAAgggMIcAwX4OvDysXxCRm/3VFO+rL7/jPkmSjaZX3bn1EOznKAofRQABBBDotQDBvtflZecQQAABBGYUINjPCLfIjxHsF6nLuhFAAAEEYhYg2MdcPdqOQH8F8nNT/Q5aecQckXP9FWDPuhYg2HddgYrtE+wVFoUmIYAAAgioECDYqygDjUAAgZIA5yYOia4FCPZdV4Bgr7ACNAkBBBBAQKsAF89aK0O7EFhtAc5Nq11/DXtPsNdQhVIb6LFXWBSahAACCCCgQoCLZxVloBEIIECPPceAMgGCvbKCuOYQ7BUWhSYhgAACCKgQINirKAONQAABgj3HgDIBgr2yghDsFRaEJiGAAAIIqBEg2KspBQ1BAAFPgHMTh0PXAgT7ritQsX167BUWhSYhgAACCKgQ4OJZRRloBAII0GPPMaBMgGCvrCD02CssCE1CAAEEEFAjQLBXUwoaggAC9NhzDCgSINgrKkbRFHrsFRaFJiGAAAIIqBAg2KsoA41AAAF67DkGlAkQ7JUVhB57hQWhSQgggAACagQI9mpKQUMQQIAee44BRQIEe0XFoMdeYTFoEgIIIICAKgGCvapy0BgEEMgFODdxKHQtQLDvugIV22covsKi0CQEEEAAARUCXDyrKAONQACBkgDnJg6JrgUI9l1XgGCvsAI0CQEEEEBAqwAXz1orQ7sQWG0Bzk2rXX8Ne0+w11CFUhvosVdYFJqEAAIIIKBCgItnFWWgEQggQI89x4AyAYK9soK45hDsFRaFJiGAAAIIqBAg2KsoA41AAAGCPceAMgGCvbKCEOwVFoQmIYAAAgioESDYqykFDUEAAU+AcxOHQ9cCBPuuK1CxfXrsFRaFJiGAAAIIqBDg4llFGWgEAgjQY88xoEyAYN9CQdI0vVZELojI9mAwuLdY5fr6+uEsy7a9Tbxqrb11b2/vpUmbJdi3UBRWgQACCCDQSwGCfS/Lyk4hEL0A56boSxj9DhDs5yzhoUOH7rTW3iciXxWRH1UE+00ROTEYDK6EbopgHyrFcggggAACqybAxfOqVZz9RSAOAc5NcdSpz60k2LdU3Tzg30CwbwmU1SCAAAIIIFAhwMUzhwUCCGgU4NyksSqr1SaCfUv1nhDsR0PxkyTZ2NnZudS0SXrsm4T4OQIIIIDAqgpw8byqlWe/EdAtwLlJd31WoXUE+5aqXBXs/VWvra3daIw5Z6095j9jn6bpUyJyrNyMs2fPttQyVoMAAggggEB/BG68clQOZpdrd+iVt9wv33/Tbf3ZYfYEAQSiEFilc5PLNGmaHo+iMCvUSIJ9S8VuCvZuM2maPmCMuby7u/vkpM3SY99SUVgNAggggEDvBOgV611J2SEEeiHAuakXZYx6Jwj2LZWPYN8SJKtBAAEEEEBgggAXzxweCCCgUYBzk8aqrFabCPYt1bsq2Kdp+kkReWYwGLxWNxS/avP02LdUFFaDAAIIINA7AS6ee1dSdgiBXghwbupFGaPeCYL9nOXLA/0TpdWccbPje++3v1lEgt5h79ZDsJ+zKHwcAQQQQKC3Alw897a07BgCUQtwboq6fL1oPMFeYRkJ9gqLQpMQQAABBFQIcPGsogw0AgEESgKcmzgkuhYg2HddgYrtE+wVFoUmIYAAAgioEODiWUUZaAQCCBDsOQaUCRDslRXENYdgr7AoNAkBBBBAQIUAwV5FGWgEAggQ7DkGlAkQ7JUVhGCvsCA0CQEEEEBAjQDBXk0paAgCCHgCnJs4HLoWINh3XYGK7dNjr7AoNAkBBBBAQIUAF88qykAjEECAHnuOAWUCBHtlBaHHXmFBaBICCCCAgBoBgr2aUtAQBBCgx55jQJEAwV5RMYqm0GOvsCg0CQEEEEBAhQDBXkUZaAQCCNBjzzGgTIBgr6wg9NgrLAhNQgABBBBQI0CwV1MKGoIAAvTYcwwoEiDYKyoGPfYKi0GTEEAAAQRUCRDsVZWDxiCAQC7AuYlDoWsBgn3XFajYPkPxFRaFJiGAAAIIqBDg4llFGWgEAgiUBDg3cUh0LUCw77oCBHuFFaBJCCCAAAJaBbh41loZ2oXAagtwblrt+mvYe4K9hiqU2kCPvcKi0CQEEEAAARUCXDyrKAONQAABeuw5BpQJEOyVFcQ1h2CvsCg0CQEEEEBAhQDBXkUZaAQCCBDsOQaUCRDslRWEYK+wIDQJAQQQQECNAMFeTSloCAIIeAKcmzgcuhYg2HddgYrt02OvsCg0CQEEEEBAhQAXzyrKQCMQQIAee44BZQIEe2UFocdeYUFoEgIIIICAGgGCvZpS0BAEEKDHnmNAkQDBXlExiqbQY6+wKDQJAQQQQECFAMFeRRloBAII0GPPMaBMgGDfQkHSNL1WRC6IyPZgMLjXX2Wapg+IyGn3b8aYu3Z3d59s2iTBvkmInyOAAAIIrKoAwX5VK89+I6BbgHOT7vqsQusI9nNW+dChQ3daa+8Tka+KyI/8YJ//7BYROSEiB134T5Lk9M7OzqVJmyXYz1kUPo4AAggg0FsBLp57W1p2DIGoBTg3RV2+XjSeYN9SGfMQf0MR7NM0dUH+sSRJtoogX16mbtME+5aKwmoQQAABBHonwMVz70rKDiHQCwHOTb0oY9Q7QbBvqXwVwd4Nz39ERO4eDAavuc2sr68fzrJs0/XgDwaDKwT7lvBZDQIIIIDAyghw8bwypWZHEYhKgHNTVOXqZWMJ9i2VtRzs19bWbjTGPCgid0wK9mmaPiUix8rNOHv2bEstYzUIIIAAAgj0R+DGK0flYHa5dodeecv98v033dafHWZPEEAgCoFVOjcZY86laXo8isKsUCMJ9i0Vmx77liBZDQIIIIAAAhME6BXj8EAAAY0CnJs0VmW12kSwb6neNcH+aWvtqb29vZfcZnjGviVsVoMAAgggsLICXDyvbOnZcQRUC3BuUl2elWgcwb6lMleFdv/f8lfijQX9uk0zeV5LRWE1CCCAAAK9E+DiuXclZYcQ6IUA56ZelDHqnSDYz1m+PLw/UVrNGTc7fjEzvogcdT9PkmSj6VV3bjmC/ZxF4eMIIIAAAr0V4OK5t6VlxxCIWoBzU9Tl60XjCfYKyzhrsLcXZUOMPDRpl8yG3KRwl2kSAggggAACQQJcPAcxsRACCKiwlQEAABycSURBVCxZgHPTksHZ3D4Bgr3Cg2LOYH9xwi790GzI2xTuMk1CAAEEEEAgSICL5yAmFkIAgSULcG5aMjibI9jHcAwQ7GOoEm1EAAEEEOhCgIvnLtTZJgIINAlwbmoS4ueLFqDHftHCM6yfYD8DGh9BAAEEEFgJAS6eV6LM7CQC0QlwboquZL1rMMFeYUkJ9gqLQpMQQAABBFQIcPGsogw0AgEESgKcmzgkuhYg2HddgYrtE+wVFoUmIYAAAgioEODiWUUZaAQCCBDsOQaUCRDslRXENYdgr7AoNAkBBBBAQIUAwV5FGWgEAggQ7DkGlAkQ7JUVhGCvsCA0CQEEEEBAjQDBXk0paAgCCHgCnJs4HLoWINh3XYGK7dNjr7AoNAkBBBBAQIUAF88qykAjEECAHnuOAWUCBHtlBaHHXmFBaBICCCCAgBoBgr2aUtAQBBCgx55jQJEAwV5RMYqm0GOvsCg0CQEEEEBAhQDBXkUZaAQCCNBjzzGgTIBgr6wg9NgrLAhNQgABBBBQI0CwV1MKGoIAAvTYcwwoEiDYKyoGPfYKi0GTEEAAAQRUCRDsVZWDxiCAQC7AuYlDoWsBgn3XFajYPkPxFRaFJiGAAAIIqBDg4llFGWgEAgiUBDg3cUh0LUCw77oCBHuFFaBJCCCAAAJaBbh41loZ2oXAagtwblrt+mvYe4K9hiqU2kCPvcKi0CQEEEAAARUCXDyrKAONWJCAvSjvaVq1OSIvNi3Dz5cvwLlp+eZscVyAYK/wiCDYKywKTUIAAQQQUCHAxbOKMtCIBQnYi/IpMfLQhNVvmw05sqDNs9o5BDg3zYHHR1sRINi3wli9kvX19cNZlm17P33VWnvr3t7eS5M2S7BfYFFYNQIIIIBA1AJcPEddPhrfIECwj/cQ4dwUb+360nKC/QIrmQf7TRE5MRgMroRuimAfKsVyCCCAAAKrJsDF86pVfLX2l2Afb705N8Vbu760nGC/wEoS7BeIy6oRQAABBFZSgIvnlSz7yuw0wT7eUnNuird2fWk5wX6BlSwPxU+SZGNnZ+dS0ybpsW8S4ucIIIAAAqsqwMXzqlZ+NfabYB9vnTk3xVu7vrScYL+kSq6trd1ojDlnrT3mP2OfpulTInKs3IyzZ89O3bKfvTqQG/73ydrPXTU/Ky/+zMWp19u3D/ydH2/J3/7xVu1u/fBNG/LyWx7s226zPwgggMDUAtf/n1Py1tf9qWLGV/HdN98uf/VTvzH1euf5wI1XjsrB7HLtKl55y/3y/TfdNs8m+CwCnQn8wk+ekXf+3z+s3f5fH0jl8k9Pf43Y2Q6t0IZX6dzkMk2apsdXqLxR7CrBfollStP0AWPM5d3d3ScnbZYe+8UWxV6U+8XIpyds5TmzIR9cbCtYOwIIIKBfwG7Ll0XkA7UtNfKwOSz3LHNP6BVbpjbbWrYAPfbLFm9ve5yb2rNkTbMJEOxnc5vpUwT7mdha/xDBvnVSVogAAj0VINj3tLDslloBgr3a0jQ2jGDfSMQCCxYg2C8QOE3TT4rIM4PB4LW6ofhVm6fHfoFFERGC/WJ9WTsCCPRHgGDfn1qyJ3EIEOzjqFNVKwn28dauLy0n2C+wkmmaXisiF0TkZhEJeoe9aw7BfoFFIdgvFpe1I4BArwQI9r0qJzsTgQDBPoIi1TSRYB9v7frScoK9wkoS7BdbFHrsw3zttriZFt9au7SVp80ReThsbSyFAAIxChDsY6wabY5ZgGAfb/UI9vHWri8tJ9grrCTBfrFFIdiH+ebBfmNCsL+HYB9myVIIxCpAsI+1crQ7VgGCfayVEyHYx1u7vrScYK+wkgT7xRaFYB/mS7APc2IpBPosQLDvc3XZN40CBHuNVQlrE8E+zImlFidAsF+c7cxrJtjPTBf0QYJ9EJO78+yG4tNjH8bFUgj0UoBg38uyslOKBQj2iovT0DSCfby160vLCfYKK0mwX2xRCPZhvgT7MCeWQqDPAgT7PleXfdMoQLDXWJWwNhHsw5xYanECBPvF2c68ZoL9zHRBH9QY7O22PDWx8UZ+aA7LPUE72NJCGoN9o5OVPzVH5LmWCIJWE9CmR8wReTFoZT1dyF6UDTFyx6TdMxtyvKe7H/VuEeyjLh+NbxCwF+UDYuSfaTo3EezjPWwJ9vHWri8tJ9grrCTBfrFFURzsj9XuuZGHCfbDiWm+LSK/WOtk5YMdBHs78Yi1chPBfhjs3aMddX9+aDbkbYv95rP2WQQI9rOo8ZlYBPJg/+UJ7X3FbMi7lrk/BPtlare7LYJ9u56sbXoBgv30Zgv/BMF+scQE+zBfpT32BPuw8qlaKu+xJ9irqkpYYwj2YU4sFacAwT7OumltNcFea2VWp10Ee4W1JtgvtigE+zBfgn2wEz32DVQE+7BjSeNSBHuNVaFNbQkQ7NuSZD1OgGDPcdC1AMG+6wpUbJ9gv9iiEOzDfAn2wU4Ee4J92MES4VIE+wiLRpODBQj2wVQsGCBAsA9AYpGFChDsF8o728r7FOztRal/bjznMUfk3GxSs32KYB/mRrAPdiLYE+zDDpYIlyLYhxUt4HfdK+aIbIetbf6l7EV5q4h8oGFN2+aIvDL/1sLWYC/Ke0SG/6v908H1gJs8j2fsw0qoaqmA75ws/Xjalm9OPMatHF92m1QVjcYsXIBgv3Di6TfQu2BvJs74/qLZkJumV5r9EwT7MDuCfbATwZ5gH3awRLgUwT6saHZbfiAyDNPVf6wcWXqwN8M21f+x8q6lB3szDD71wd5Ns7nEP/TYLxG75U01npus/LY5Ive3vNnJXymC/TK52VaFwFJPoFQgTIBgH+Y061IE+zA5gn2wE8GeYB92sES4VOPFczdv7FDXK0awbz64hz32BPtGKGbFbyQaLtB4biLYh0GyVK8ECPYKy0mwX2xRCPZhvgT7YCeCPcE+7GCJcKnGi2eCfREy6LFvPg8Q7APOAQT7ACSCfRgSS62cAMFeYckJ9ostCsE+zJdgH+xEsG++oOc99mGHk7qlCPZhJaHHvtmJHvtmo2FP9EX5lBh5aMLS22ZDjoStrb9LNZ6b6LHvb/HZs1oBgr3Cg4Ngv9iiEOzDfAn2wU4E+wiDfT6R18SWmyPyYthR0M5SKtu0PZxYrH4SNnrs6bEPPPwJ9mFQGoN9lOcmgv0b56Y3Jq1U9buuqT38fHYBgv3sdgv7JMF+YbTFSe5+MfLpCVt5zmzIBxfbivG12+3hBIP1bxDo5uL5oohs1DpYuccckYeX7PRtEfnFCW36oDkizy25TQT7OIP9MdE2secleUisfErZuYlgH3BCoce+GYlg32yUBzF1Pfa2+dx0zmzI8bA9bGcpeuzDHLWdm8Ja/f+XStP0WhF52lp7am9v76VJnz906NCd1tobBoPBvdNupy/LE+wXXMk0TR8QkdNuM8aYu3Z3d59s2iTBvklovp/TYx/mR499sBPBnmAfdrA0OTVfPHdx05FgH1BdbRfPw9fdMSt+Y+WYFb+RaLgAwT7QSeGs+NrOTWGSBPtpnYrlCfazygV8Lr9zdIuInBCRgyJyIUmS0zs7O5cmfZxgH4A7xyIE+zA8gn2wE8G+KbBeFHXP2A/fgUyPfeNB3tgr1s1oImbFb/7OEewbj+7hMGXeYx/i1HzTkR77Nyb049wUcDxNswg99tNoyXLfFzpd0+JeOk1TF+QfS5JkqwjyoUNECPaLrT3BPsyXYB/sRLBvDhkE+4DDKaBXjB57Lp4DjqRhYCXYB0gR7AOQ6LEPQ+LcFOw0zYIE+2m0CPbTaU2xdH4gPiIidw8Gg9fcR9fX1w9nWbbpevAHg8GVutUR7KeAnmFRgn0YGsE+2IlgT7APO1ianJp7xQj2XDwHHWsE+yAmeuzDmBiKH+q0oj32RcdlzuQeP35BRH5dRP6tiBwVkVettbcWz8ivra3daIx5XkSuyz9zxn8u3n+MOf/58PPGmFcndZqWO1Dz3LXtr6PpOf3AUqtdjKH4CypNftA+KCJ3TAr2aZpOnjRtQe1jtQgggAACCCCAAAIIIIDALAJJkty0s7PzYh6on0iSZMONUs6D+YeLMO8/mmytvc4Yc85ae8yF7GKEszHma24eMn9Z1wmah3M3ed5UwT7PYZ8UkVNuPVW5bJZ91v4Zgv2CKtRFj/2CdoXVTiEw62iLKTbBogsQoG4LQF3SKqndkqAXsBlqtwDUJaySui0BeUGboHYLgl3warXXraanfDRC2R+xbIxxgX9s5nrv53eLyCP+Y8z+UPxpeuyLmw2l0oyNHFhw2TpZPcF+QexVz4Qs+hn7Be0Kq51CQPvJd4pdWalFqVu85aZ21C5egThbzncuzrq5VlO7OGunvW6Kg/3KvfqOYL/A77h/oE8z+YP2L/ACyaJfNbWLs4TULc66caEab92oXby143xJ7eIViLPl2r9z0wT7pqH4+TD+dxbzkeXrvq8Y1p//XNwz+Xm2uiAi2+6//XbkQ+/9If/Xisjtg8Hgc3EeBWGtJtiHOc20VPHcSD5xhBTPnjStTPsXuKn9q/xzahdn9albnHUjHMZbN2oXb+04X1K7eAXibLn279w0wd57br6Y1E6MMXe55+vz3wvDt4oV2cla+1vGmF+x1p5yz+SXJt57wVr7FWPMz5WDvVtXafI8N6HfbcW8Z3EeCc2tJtg3G7EEAggggAACCCCAAAIIIIAAAmoFCPZqS0PDEEAAAQQQQAABBBBAAAEEEGgWINg3G7EEAggggAACCCCAAAIIIIAAAmoFCPZqS0PDEEAAAQQQQAABBBBAAAEEEGgWINg3G7EEAggggMACBUJfBdrUhHxSnQdF5I6+T5DTZKHl524GY2PM5WJipFnb1dYxErp9/1jKP/N0MXmTv45ltyu0/X1dju94XyvLfs0qMOkcO80buWbdPp/TJUCw11WPmVrjve7h5nwF591rIvK/P5YkydbOzs6lYuX+LJH+TJQzbZwPzSyQXxA+4a3g1eJ1HjOvlA+2IlDUpvz9yC8qPykip9zMrq1sbEVWUnG8j2aobSsctXHRXz6fhr7NJLSMdfvaVgAObUdby1X8/inPcNx5sC+/9sjte9FuY8yWf9OhqEOWZX9hjBneJCLY7z9aSjNTL+13Vxvf8baO/ZjWUzr/Dq8R+R0WUwXr20qw70cd29oLgn1bkh2tpwjp/sWn+zdr7fXW2i+6V0aUg71ralsX0h3tdi82Sw30ljGvzUnXQmvtMfeKFfd3gv3sNSsf7/l/3+IuMI0xH7bW3uBeVzP7Fub/ZBH2kiQ57W6G5q8s/biIPN7WRXBPg/2oN7vCsJVgP091i1fP+r8LvWD69SLk1PVu0es1rt/l+6EJ9tN/E/xzbfGqMbcWv8Nn+rXyiRgE2jp38b2LodpvtJFgH0+t9rW0fAFVXqDqYqZYhlDZfeGpQfc1qGtBURs3hNhaOwyf7oKIYD97zcrHe37+ekRE7jbGvF9DsF9Gffse7Isbx+7/XU+4lpEIrh2uTcXNo7wOh0TkuuLRjbqL17Yujmf/9uj6ZN6hcGsXN+IIGNMfC+7YT5LkeYL89Haxf6Ktcxffu3iOBIJ9PLXa19L8l+tm3ZAqgr3u4tZd4HsXnD8vIteLyG1Jkrw7y7LtfI9GQ5h172G8rStqIyKfcaNejDFfcyGlHPxKw1HFjZzJsmzHHylT0YN5rYgMA+0q1bV8vPsXCn6wL5/XyhcmxXlNRI7mR9jdIvKPXTiz1r69PHxaRM6JyL/LA9xoCGrVUGJjzPdE5ELRY19xs9TV7oKIDB97co9qWGu/IiJP+9tx/26Medn7zp4pBcp9oxPKATgPoqfddqy1v2WM+ZWqZ7y7/pZVXTj6+1L3d9fucq39x8RExNXqfxljdt13zz9+vGPH1fZPcoORsW8nIsN/rziu3EiC/2yt/UjRk1+zjX1D8fP1u1EmtyZJ8vc13JRa5nFQ9WiDv/1SHceG6VfVpjiGROTP3bmxeASq6vx69erV7+bf8craL9Mhlm2Ve+z9dpfPO/73REQO5ue2oi5/YK097K5JijlM/BtmVXU/cODAL2RZdsb/jP89qzoeYnFdZDvL1++TriPco4H+PCYlU9fM0Xew9J16wf3+Msb8XPH7aUINi+tPt77hOZXaLfIImH3dBPvZ7Tr/JMG+8xLM1YC6Z47zkHNf8bx9W3dc52rsin3Yv/DIv2duqPGteZgbPmOfX/QMA7q7yPHr5C723bIukOSPxtxrrf0vXsBw63LP71ZOyNVH7ooe+1EPaoX36IZlRbAf63nNLy423IVjRbB3IfzlfM4Rd5E6DO3lmy81oWTsBtqEZ7KLsD/cjrX2OmPM8yLyxfziZ/jz4mZBxfd+tPki0JQvxPP/Hp0TNB0f5fpUDNMeDcWfFCJyt3PFoy/FBagx5jM1wX5k7G8zDxL7bnj77cxv4IxGixTfVb9ns27yvDzIj0bxrOrIK+84Hnteu+bm53CuAncj01nnj7m478Xw/FfcUBOR7SJgFPVPkuQOv6fZCybD71fTTQZN35Wu2uLfDC3PGxMQ7N05dFiXmrA5rKH/u9Eb3fZgkiSfyLLMjRgYzvXkfw/rvqtdOWnbrvuONV1HFAG7CPZVj11kWTa8finfuPbmRxnWd9J31//d6q53mvKHNstVag/BPuJqN32x6LHXXdyGHvuxHr3izmjbE3npFuqudTUh9J1Zlj2UJIn7ZXsqSZJ1r0d21FhXo7xXaXgDwFr7qQMHDnw9yzIXNlzvsvvscFjkKtW1ItBW9mJP6rHPL0zGbob4Aayqx97v5fYvYov21E0g6rW3sse3KHjdiALvQtbdUBjNddI0FL9qbhTNN/cqJs/b10NbXHROChFV8yxU1Gt4XiwPC/V/12VZ9q18VIUr0ahn0f1HEdzd37MsGw4l9y5m73MjdKy1n3NzalQFe9fzJSJuJNVo4rFVDfbe8e9utJ0u3ZTyJ4V1i9b1GBajnFzNxr7Xda6Tas9Q88m/M73v6ju8joOxOTCqeuz9c6gfHP3vbM0Ny2Hd/QCf/94c3njLb467Gwf7vqvd/fbXs2U/aDddR+SPDe6bV6vpRor/PZtUw/zGzeiNM96xRO30HDLDlhDslRVkmuY0XewR7KfRXP6y0wT7/KJ0GBBExA3JvbWY0G35Le//FiuCfdEru5fvfRHsKx+Fyb97rrfi37sAkQ/pvy8f+vsPXW+9N5RxJeo6KQCF9ti3GezLwaTqplnTRVH+vRz1PLrvZEWv1ioE+9qRJ6FD8dsK9kW4q5ocrzjO3EWwe1TC60F8xN2IybLsnxdvvKgI9heMMT+w1r6tblhx/8+M1XtY91iNv7TXa+z+eeytPfnNGIL9kg6g8lB4fxh3U7AvzolZln3a3eQuboRNOr+XRsu4kRtjz/tXfVeXRKF6M6HXEcU5tummcNUIiYpgXzmJbd0z9tRO3yFEsNdXk6laVDVEk1nxpyLsbOHQYO9+KRpj3ru7u/vVSTdrOtuRHm64qjbes2fF6yRHQ7urZlDPf9n+sog8WwzJz7LsD9z8XcVQ/lWqa2iwLw+t9c9xxhjXY+pubv1VMWS3YSj+WFgoXQC9bzAYPJuH82GvVf5c/GhSsIrh26Mh9cX30lr7Db+3cd5gX0w4JyLvLHqGYxqKXz4dVPS6D4ex58u5Wg6DXt6TNxwy6vWYPz9hKL7fezS6efL666//jTHmb8q97u5GWn5s/Ru3QWvt7xY3R4vnhP2AUzcUv/zM8Cr22PtDhJ1lxaiZ0SMV+XfodhF5xn8kxX+jT1WwL58H3H9ba3/G1baYRyN/BGrsxlkPfx3NtUtFOCwCuFtZRZir/E4Wz9iX5/YofrdZa/9naWLZfXUfDAaf87Y5NlnlTTfddKjuuzrXTvfow03XEe6xh/LN07rfHY7FPSZWPN5SMxS/soblYE/t9B5kBHu9tQluWWmyC/e5YmKLoiewmGTK/ewFY8zvW2v/NP+S3+W/wzd4oyw4t0BosPd+KRbDG0dDmOduBCuoFKiqTbnHyXuO0D3r62bWHhuC7D+bn/fkDnv9/fdml4a+9bquocG+CNpueG8ewMYmjqsY+j1x8ry6ofgVE7UNh1eXhyP6PfnliYdcz21+APmvexsLGuWg3zQUPw/2Y+fu2CbP879UpYtOf/JBd5Pms/lEhFX2IZPn3VEOd8X8CcXkin79qr7Drq1Vr42tC/buu+w/xpEfo52/qnHZp/LSxFlV5759k72Wvlufd4815CMl9g3F9+uS79vwhmo+F0PlTR2G4lcfBRXnzNG8CKWfjX0n64J93fwHpXPq2Bwl5Tkz8vP82HmORw331y/kOqJ0jp34u6Nco4bJ80Y1LE1a6yZDHE4sXHWeXfa5iO2NCxDsOSIQQAABBKIVaJprJNod8xpeNwyyD/tWtw+MTupzddm3VRNYxXNYDDUuz3sSQ5tp42QBgj1HCAIIIIBANAJpmn7IWvuX/vPsxesIo9mJhoa6mxVukaIH0n+lVF/2sbwfxZDtYuhufsNm7DVZfd139guBvguswjlMew3zm6UfF5HHvRGHo6H32ttP+8IECPZhTiyFAAIIIKBAoOI99r18hKE01HnslWIKyrCQJkx6//lCNshKEUBgoQJMrrZQ3qlXXnqcbPhWCh5hmZpR9QcI9qrLQ+MQQAABBBBAAAEEEEAAAQQQmCxAsOcIQQABBBBAAAEEEEAAAQQQQCBiAYJ9xMWj6QgggAACCCCAAAIIIIAAAggQ7DkGEEAAAQQQQAABBBBAAAEEEIhYgGAfcfFoOgIIIIAAAggggAACCCCAAAIEe44BBBBAAAEEEEAAAQQQQAABBCIWINhHXDyajgACCCCAAAIIIIAAAggggADBnmMAAQQQQAABBBBAAAEEEEAAgYgFCPYRF4+mI4AAAggggAACCCCAAAIIIECw5xhAAAEEEEAAAQQQQAABBBBAIGIBgn3ExaPpCCCAAAIIIIAAAggggAACCBDsOQYQQAABBBBAAAEEEEAAAQQQiFiAYB9x8Wg6AggggAACCCCAAAIIIIAAAgR7jgEEEEAAAQQQQAABBBBAAAEEIhYg2EdcPJqOAAIIIIAAAggggAACCCCAAMGeYwABBBBAAAEEEEAAAQQQQACBiAUI9hEXj6YjgAACCCCAAAIIIIAAAgggQLDnGEAAAQQQQAABBBBAAAEEEEAgYgGCfcTFo+kIIIAAAggggAACCCCAAAIIEOw5BhBAAAEEEEAAAQQQQAABBBCIWIBgH3HxaDoCCCCAAAIIIIAAAggggAACBHuOAQQQQAABBBBAAAEEEEAAAQQiFiDYR1w8mo4AAggggAACCCCAAAIIIIAAwZ5jAAEEEEAAAQQQQAABBBBAAIGIBQj2ERePpiOAAAIIIIAAAggggAACCCBAsOcYQAABBBBAAAEEEEAAAQQQQCBiAYJ9xMWj6QgggAACCCCAAAIIIIAAAggQ7DkGEEAAAQQQQAABBBBAAAEEEIhYgGAfcfFoOgIIIIAAAggggAACCCCAAAIEe44BBBBAAAEEEEAAAQQQQAABBCIWINhHXDyajgACCCCAAAIIIIAAAggggADBnmMAAQQQQAABBBBAAAEEEEAAgYgFCPYRF4+mI4AAAggggAACCCCAAAIIIECw5xhAAAEEEEAAAQQQQAABBBBAIGIBgn3ExaPpCCCAAAIIIIAAAggggAACCBDsOQYQQAABBBBAAAEEEEAAAQQQiFiAYB9x8Wg6AggggAACCCCAAAIIIIAAAgR7jgEEEEAAAQQQQAABBBBAAAEEIhb4fw380mJ3IA5UAAAAAElFTkSuQmCC";
		Map<String, Object> resultTable = new LinkedHashMap<String, Object>();
		resultTable.put("summaryList", new ArrayList<FunctionalSummary>());
		resultTable.put("moduleList", new ArrayList<FunctionalModule>());
		resultTable.put("faillogList", new ArrayList<FunctionalFailLog>());
		resultTable.put("picBase64Info", picBase64Info);
		String fileName = "test";
		try {
//			new PDFUtils().testIMG(fileName, resultTable);
			new PDFUtils().justTest(resultTable);
		} catch (IOException e) {
			e.printStackTrace();
		}

	}
	
	
	
	@SuppressWarnings("deprecation")
	private Table createSummaryReportTable(List<FunctionalSummary> summaryList) throws IOException {
		//初始化table，根据ACOS判断表格的列数
		Table table = null;
		for (FunctionalSummary functionalSummary : summaryList) {
			if(functionalSummary.getProject().equals("ACOS")) {
				table = new Table(14);
				break;
			}else {
				table = new Table(13);
				break;
			}
		}
		
		
		table.setMargins(2, 0, 14, 10).setWidthPercent(90).setFontSize(5f);

		// First Row
		Cell cell = new Cell(1, 14).add(new Paragraph("Summary Report").setFontColor(Color.WHITE));
		
		cell.setTextAlignment(TextAlignment.CENTER).setPadding(5).setBackgroundColor(TITTLE_BG);
		table.addHeaderCell(cell);

		// Set table header
		table.getHeader().setBackgroundColor(HEADER_BG);
		table.addHeaderCell(new Cell().add("Test Date"));
		table.addHeaderCell(new Cell().add("Version"));
		table.addHeaderCell(new Cell().add("Cycle"));
		table.addHeaderCell(new Cell().add("TestCase"));
		table.addHeaderCell(new Cell().add("Time(/s)"));
		for (FunctionalSummary functionalSummary : summaryList) {
			if(functionalSummary.getProject().equals("ACOS")) {
				table.addHeaderCell(new Cell().add("Assertions"));
				break;
			}
		}
		
		table.addHeaderCell(new Cell().add("Pass"));
		table.addHeaderCell(new Cell().add("Fail"));
		table.addHeaderCell(new Cell().add("Error"));
		table.addHeaderCell(new Cell().add("Skip"));
		table.addHeaderCell(new Cell().add("Incomplete"));
		table.addHeaderCell(new Cell().add("Risk"));
		table.addHeaderCell(new Cell().add("Pass Rate(%)"));
		table.addHeaderCell(new Cell().add("Final Result"));

		if (summaryList.size() > 0) {
			for (FunctionalSummary functionalSummary : summaryList) {				
				table.addCell(new Cell().add(functionalSummary.getTestDate()));
				table.addCell(new Cell().add(functionalSummary.getVersion()));
				table.addCell(new Cell().add(functionalSummary.getCycle()));
				table.addCell(new Cell().add(functionalSummary.getTestCase()));
				table.addCell(new Cell().add(functionalSummary.getTime()));
				if(functionalSummary.getProject().equals("ACOS")) {
					table.addCell(new Cell().add(functionalSummary.getAssertions()));
				}
				table.addCell(new Cell().setFontColor(Color.GREEN).add(functionalSummary.getPass()));
				table.addCell(new Cell().setFontColor(Color.RED).add(functionalSummary.getFail()));
				table.addCell(new Cell().setFontColor(Color.ORANGE).add(functionalSummary.getError()));
				table.addCell(new Cell().add(functionalSummary.getSkip()));
				table.addCell(new Cell().add(functionalSummary.getIncomplete()));
				table.addCell(new Cell().add(functionalSummary.getRisk()));
				table.addCell(new Cell().add(functionalSummary.getPassRate()));
				if ("Pass".equals(functionalSummary.getFinalResult())) {
					table.addCell(new Cell().setFontColor(Color.GREEN).add(functionalSummary.getFinalResult()));
				} else {
					table.addCell(new Cell().setFontColor(Color.RED).add(functionalSummary.getFinalResult()));
				}
			}
		} else {
			table.addCell(new Cell(1, 14).setFontColor(Color.RED).add("No Results..."));
		}
		
		return table;
	}

	@SuppressWarnings("deprecation")
	private Table createModuleReportTable(List<FunctionalModule> moduleList) throws IOException {

		Table table = new Table(10);
		table.setMargins(2, 0, 14, 10).setWidthPercent(90).setFontSize(6f);

		// First Row
		Cell cell = new Cell(1, 10).add(new Paragraph("Module Detail Report").setFontColor(Color.WHITE)).setBorder(null);
		cell.setTextAlignment(TextAlignment.CENTER).setPadding(5).setBackgroundColor(TITTLE_BG);
		table.addHeaderCell(cell);

		// Set table header
		table.getHeader().setBackgroundColor(HEADER_BG);
		table.addHeaderCell(new Cell().add("Module"));
		table.addHeaderCell(new Cell().add("TestCase"));
		table.addHeaderCell(new Cell().add("Pass"));
		table.addHeaderCell(new Cell().add("Fail"));
		table.addHeaderCell(new Cell().add("Error"));
		table.addHeaderCell(new Cell().add("Skip"));
		table.addHeaderCell(new Cell().add("Incomplete"));
		table.addHeaderCell(new Cell().add("Risk"));
		table.addHeaderCell(new Cell().add("Pass Rate(%)"));
		table.addHeaderCell(new Cell().add("Result"));

		if (moduleList.size() > 0) {
			for (FunctionalModule functionalSummary : moduleList) {
				table.addCell(new Cell().add(functionalSummary.getModule()));
				table.addCell(new Cell().add(functionalSummary.getModuleTestCase()));
				table.addCell(new Cell().setFontColor(Color.GREEN).add(functionalSummary.getPass()));
				table.addCell(new Cell().setFontColor(Color.RED).add(functionalSummary.getFail()));
				table.addCell(new Cell().setFontColor(Color.ORANGE).add(functionalSummary.getError()));
				table.addCell(new Cell().add(functionalSummary.getSkip()));
				table.addCell(new Cell().add(functionalSummary.getIncomplete()));
				table.addCell(new Cell().add(functionalSummary.getRisk()));
				table.addCell(new Cell().add(functionalSummary.getModulePassRate()));
				if ("Pass".equals(functionalSummary.getModuleResult())) {
					table.addCell(new Cell().setFontColor(Color.GREEN).add(functionalSummary.getModuleResult()));
				} else {
					table.addCell(new Cell().setFontColor(Color.RED).add(functionalSummary.getModuleResult()));
				}
			}
		} else {
			table.addCell(new Cell(1, 10).setFontColor(Color.RED).add("No Results..."));
		}
		
		return table;
	}

	@SuppressWarnings("deprecation")
	private Table createDetailFailedReportTable(List<FunctionalFailLog> faillogList) throws IOException {

		Table table = new Table(6);
		table.setMargins(2, 0, 14, 10).setWidthPercent(90).setFontSize(6f);

		// First Row
		Cell cell = new Cell(1, 6).add(new Paragraph("Detail Information For Failed Test Case").setFontColor(Color.WHITE));
		cell.setTextAlignment(TextAlignment.CENTER).setPadding(5).setBackgroundColor(TITTLE_BG);
		table.addHeaderCell(cell);

		// Set table header
		table.getHeader().setBackgroundColor(HEADER_BG);
		table.addHeaderCell(new Cell().add("Module"));
		table.addHeaderCell(new Cell().add("Function"));
		table.addHeaderCell(new Cell().add("CaseName"));
		table.addHeaderCell(new Cell().add("Screenshot"));
		table.addHeaderCell(new Cell().add("Log"));
		table.addHeaderCell(new Cell().add("Result"));

		if (faillogList.size() > 0) {
			for (FunctionalFailLog functionalSummary : faillogList) {
				table.addCell(new Cell().add(functionalSummary.getModule()));
				table.addCell(new Cell().add(functionalSummary.getFunction()));
				table.addCell(new Cell().add(functionalSummary.getCaseName()));
				if (!"".equals(functionalSummary.getScreenshot()) && functionalSummary.getScreenshot() != null) {
					// Format path if include "\"
					if (functionalSummary.getScreenshot().indexOf("\\") > -1) {
						functionalSummary.setScreenshot(functionalSummary.getScreenshot().replaceAll("\\\\", "/"));
					}
					Link img = new Link("ScreenShot Image", PdfAction.createURI(SERVER.concat(functionalSummary.getScreenshot())));
					table.addCell(new Cell().add(new Paragraph().add(img).setBorder(null)).setFontColor(Color.BLUE));
				} else {
					table.addCell(new Cell().add("-"));
				}

				// Format path if include "\"
				if (functionalSummary.getLog().indexOf("\\") > -1) {
					functionalSummary.setLog(functionalSummary.getLog().replaceAll("\\\\", "/"));
				}
				Link log = new Link("Logs", PdfAction.createURI(SERVER.concat(functionalSummary.getLog())));
				table.addCell(new Cell().add(new Paragraph(log).setBorder(null).setFontColor(Color.BLUE)));
				if ("ERROR".equals(functionalSummary.getCaseResult())) {
					table.addCell(new Cell().setFontColor(Color.RED).add(functionalSummary.getCaseResult()));
				} else {
					table.addCell(new Cell().setFontColor(Color.YELLOW).add(functionalSummary.getCaseResult()));
				}
			}
		} else {
			table.addCell(new Cell(1, 6).setFontColor(Color.RED).add("No Results..."));
		}
		
		return table;
	}

	public Image convImage(String picBase64Info){
		if (picBase64Info == null || "".equals(picBase64Info)) // Image data is null
		{
			return null;
		}
		String[] str = picBase64Info.split("base64,");
		String pic = str[1];
		byte[] imageBytes = Base64.decode(pic);
		int pos = picBase64Info.indexOf("base64,");
		try {
			if (picBase64Info.startsWith("data") && pos > 0) {
				byte[] img = Base64.decode(picBase64Info.substring(pos + 7));
				return new Image(ImageDataFactory.create(img));
			} else {
				return new Image(ImageDataFactory.create(imageBytes));
			}
		} catch (Exception e) {
			return null;
		}
	}
	@SuppressWarnings("deprecation")
	private Table createPerformanceCoverTable(String fileName,String reporter) throws IOException {
		Table table = new Table(1);
		table.setMargins(2, 0, 14, 10).setWidthPercent(90).setFontSize(40f);
		table.setBorder(Border.NO_BORDER);
			    
		SimpleDateFormat dateFormater = new SimpleDateFormat("yyyy-MM-dd");
		String time = dateFormater.format(new Date());
		
		String str5 = fileName;
		String str6 = "Performance Test Report";
		String str10 = "Reporter: " + reporter;
		String str11 = "Reporter Time: " + time;
		
	    table.addCell(new Cell().add("1").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("2").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("3").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("4").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str5).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str6).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("7").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("8").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("9").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str10).setFontSize(20f).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add(str11).setFontSize(20f).setFontColor(Color.WHITE).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("12").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("13").setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));
	    table.addCell(new Cell().add("14").setFontSize(10f).setFontColor(new DeviceRgb(70, 130, 180)).setBorder(Border.NO_BORDER).setBackgroundColor(new DeviceRgb(70, 130, 180)).setTextAlignment(TextAlignment.CENTER));

	    return table;
	}
	
	@SuppressWarnings("unchecked")
	public void createPerformancePdf(OutputStream os, String fileName, Map<String, Object> resultTable) throws IOException {
		List<Performance> performanceList = (List<Performance>) resultTable.get("performanceList");
		List<PerformanceBaseLine> baseLineList = (List<PerformanceBaseLine>) resultTable.get("baseLineList");
		PerformanceExport performanceExport = (PerformanceExport) resultTable.get("pExport");
		String summaryIMG = performanceExport.getSummaryIMG();
		String thoughputIMG = performanceExport.getThoughputIMG();
		summaryIMG = summaryIMG.replaceAll(" ", "+");
		thoughputIMG = thoughputIMG.replaceAll(" ", "+");
	
		PdfFont HELVETICA = PdfFontFactory.createFont(FontConstants.HELVETICA);
		PdfFont TIMES = PdfFontFactory.createFont(FontConstants.TIMES_BOLDITALIC);
		
		checkPerExport(performanceExport);
		PdfDocument pdf = new PdfDocument(new PdfWriter(os));
		Document document = new Document(pdf,PageSize.A4);
		document.setMargins(20f, 10f, 10f, 30f);
		document.add(createPerformanceCoverTable(fileName,performanceExport.getReporter1()));//设置封面
		document.add(new Paragraph("Performance Testing Report").setTextAlignment(TextAlignment.CENTER).setFont(TIMES).setFontSize(14f));
		document.add(new Paragraph(fileName.concat(" Performance Testing Result")).setUnderline().setTextAlignment(TextAlignment.CENTER).setFontSize(10f));
		document.add(new Paragraph("Background:").setFont(TIMES).setFontSize(10f));
		document.add(new Paragraph(performanceExport.getBackground1()).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(new Paragraph("Purpose:").setFont(TIMES).setFontSize(10f));
		document.add(new Paragraph(performanceExport.getPurpose1()).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(new Paragraph("Test Approach:").setFont(TIMES).setFontSize(10f));
		document.add(new Paragraph(APPROACH_TEXT).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(new Paragraph("Test scope:").setFont(TIMES).setFontSize(10f));
		document.add(new Paragraph(SCOPE_TEXT).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(new Paragraph("Test Environment:").setFont(TIMES).setFontSize(10f));
		document.add(createEnvironmentTable(performanceExport).setFontSize(8f));
		document.add(new Paragraph("Test Method:").setFont(TIMES).setFontSize(10f));
		document.add(createTestMethods().setMarginLeft(10f).setFont(HELVETICA).setFontSize(8f));
		document.add(new Paragraph("Test Scenario:").setFont(TIMES).setFontSize(10f));
		document.add(new Paragraph(SCENARIO_TEXT).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(createScenario().setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(new Paragraph("Period: ".concat(performanceExport.getTester_start1().concat(" - ".concat(performanceExport.getTester_end1())))).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f).setFontColor(TEXT_BG));
		document.add(new Paragraph(SCENARIO_TEXT1).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(new Paragraph("Test Result Summary:").setFont(TIMES).setFontSize(10f));
		document.add(convImage(summaryIMG).setWidthPercent(90f));
		document.add(createSummaryPerformanceReportTable(performanceList).setFontSize(7.5f));
		document.add(new Paragraph("Test Throughput Result:").setFont(TIMES).setFontSize(10f));
		document.add(convImage(thoughputIMG).setWidthPercent(90f));
		if (performanceList.size() > 0) {
			document.add(createPerformanceThroughputTable(performanceList).setFontSize(8f));
		}
		document.add(new Paragraph("Reference Baseline:").setFont(TIMES).setFontSize(10f));
		document.add(createBaselineTable(baseLineList).setFontSize(8f));

		document.add(new Paragraph("Test Conclusion:").setFont(TIMES).setFontSize(10f));
		document.add(new Paragraph(performanceExport.getTester_conclusion1()).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));
		document.add(new Paragraph("Test Suggestion:").setFont(TIMES).setFontSize(10f));
		document.add(new Paragraph(performanceExport.getTester_suggestion1()).setFont(HELVETICA).setFontSize(8f).setMarginLeft(10f));

		createFooterHeader handler = new createFooterHeader();
		handler.setHeader(performanceExport.getReporter1());
		pdf.addEventHandler(PdfDocumentEvent.START_PAGE, handler);
		pdf.addEventHandler(PdfDocumentEvent.END_PAGE, handler);
		document.close();
	}

	private Table createSummaryPerformanceReportTable(List<Performance> performanceList) throws IOException {

		@SuppressWarnings("deprecation")
		Table table = new Table(12);
		table.setMargins(2, 0, 14, 5).setWidthPercent(95f);

		// First Row
		Cell cell = new Cell(1, 12).add(new Paragraph("Test scenario Summary Report").setFontColor(Color.WHITE));
		
		cell.setTextAlignment(TextAlignment.CENTER).setPadding(5).setBackgroundColor(TITTLE_BG);
		table.addHeaderCell(cell);

		// Set table header
		table.getHeader().setBackgroundColor(HEADER_BG);
		table.addHeaderCell(new Cell().add("Function Type"));
		table.addHeaderCell(new Cell().add("Test Date"));
		table.addHeaderCell(new Cell().add("Samples"));
		table.addHeaderCell(new Cell().add("Average"));
		table.addHeaderCell(new Cell().add("Median"));
		table.addHeaderCell(new Cell().add("90% Line"));
		table.addHeaderCell(new Cell().add("Min"));
		table.addHeaderCell(new Cell().add("Max"));
		table.addHeaderCell(new Cell().add("Error"));
		table.addHeaderCell(new Cell().add("Throughput"));
		table.addHeaderCell(new Cell().add("KB/sec"));
		table.addHeaderCell(new Cell().add("Result"));

		if (performanceList.size() > 0) {
			for (Performance performance : performanceList) {
				table.addCell(new Cell().add(performance.getFunctionType()));
				table.addCell(new Cell().add(performance.getTestDate()));
				table.addCell(new Cell().add(performance.getSamples()));
				table.addCell(new Cell().add(performance.getAverage().concat(" ms")));
				table.addCell(new Cell().add(performance.getMedian().concat(" ms")));
				table.addCell(new Cell().add(performance.getNinetyPecLine().concat(" ms")));
				table.addCell(new Cell().add(performance.getMin().concat(" ms")));
				table.addCell(new Cell().add(performance.getMax().concat(" ms")));
				table.addCell(new Cell().add(performance.getError().concat(" %")));
				table.addCell(new Cell().add(performance.getThroughput().concat(" tps")));
				table.addCell(new Cell().add(performance.getKbSec().concat(" kb/sec")));
				if ("Pass".equals(performance.getResult())) {
					table.addCell(new Cell().setFontColor(Color.GREEN).add(performance.getResult()));
				} else {
					table.addCell(new Cell().setFontColor(Color.RED).add(performance.getResult()));
				}
			}
		} else {
			table.addCell(new Cell(1, 12).setFontColor(Color.RED).add("No Results..."));
		}

		return table;
	}

	private Table createPerformanceThroughputTable(List<Performance> performanceList) throws IOException {

		@SuppressWarnings("deprecation")
		Table table = new Table(performanceList.size());
		table.setMargins(2, 0, 14, 10).setWidthPercent(90).setFontSize(5f);

		// First Row
		Cell cell = new Cell(1, performanceList.size()).add(new Paragraph("Throughput").setFontColor(Color.WHITE));
		
		cell.setTextAlignment(TextAlignment.CENTER).setPadding(5).setBackgroundColor(TITTLE_BG);
		table.addHeaderCell(cell);

		// Set table header
		table.getHeader().setBackgroundColor(HEADER_BG);
		if (performanceList.size() > 0) {
			for (Performance performance : performanceList) {
				table.addHeaderCell(new Cell().add(performance.getFunctionType()));
				table.addCell(new Cell().add(performance.getThroughput()));
			}
		}else {
			table.addCell(new Cell(1, performanceList.size()).setFontColor(Color.RED).add("No Results..."));
		}

		return table;
	}

	private Table createBaselineTable(List<PerformanceBaseLine> baseLineList) throws IOException {

		@SuppressWarnings("deprecation")
		Table table = new Table(6);
		table.setMargins(2, 0, 14, 10).setWidthPercent(90);

		// First Row
		Cell cell = new Cell(1, 6).add(new Paragraph("Reference Baseline").setFontColor(Color.WHITE));
		
		cell.setTextAlignment(TextAlignment.CENTER).setPadding(5).setBackgroundColor(TITTLE_BG);
		table.addHeaderCell(cell);

		// Set table header
		table.getHeader().setBackgroundColor(HEADER_BG);
		table.addHeaderCell(new Cell().add("Function Type"));
		table.addHeaderCell(new Cell().add("Response BaseLine"));
		table.addHeaderCell(new Cell().add("Response Range"));
		table.addHeaderCell(new Cell().add("Throughput BaseLine"));
		table.addHeaderCell(new Cell().add("Throughput Range"));
		table.addHeaderCell(new Cell().add("Error BaseLine"));

		if (baseLineList.size() > 0) {
			for (PerformanceBaseLine baseLine : baseLineList) {
				table.addCell(new Cell().add(baseLine.getFunctionType()));
				table.addCell(new Cell().add(baseLine.getRtBaseline().concat(" ms")));
				table.addCell(new Cell().add("±".concat(baseLine.getRtRange()).concat(" ms")));
				table.addCell(new Cell().add(baseLine.getThroughputBaseline().concat(" tps")));
				table.addCell(new Cell().add("±".concat(baseLine.getThroughputRange()).concat(" tps")));
				table.addCell(new Cell().add("≤".concat(baseLine.getErrorBaseline()).concat(" %")));
			}
		} else {
			table.addCell(new Cell(1, 6).setFontColor(Color.RED).add("No Results..."));
		}

		return table;
	}

	private Table createEnvironmentTable(PerformanceExport performanceExport) throws IOException {

		@SuppressWarnings("deprecation")
		Table table = new Table(2);
		table.setMargins(2, 0, 14, 10).setWidthPercent(70);

		table.addCell(new Cell().add("Test Server").setWidthPercent(20f).setBackgroundColor(HEADER_BG));
		table.addCell(new Cell().add(performanceExport.getTest_server1()));
		table.addCell(new Cell().add("Server Port").setWidthPercent(20f));
		table.addCell(new Cell().add(performanceExport.getTest_port1()));
		table.addCell(new Cell().add("Test Network").setWidthPercent(20f).setBackgroundColor(HEADER_BG));
		table.addCell(new Cell().add(performanceExport.getTest_network1()));
		table.addCell(new Cell().add("Test Tool").setWidthPercent(20f));
		table.addCell(new Cell().add(performanceExport.getTest_tool1()));
		table.addCell(new Cell().add("Target Website").setWidthPercent(20f).setBackgroundColor(HEADER_BG));
		table.addCell(new Cell().add(performanceExport.getTest_target1()));
		table.addCell(new Cell().add("Test Data").setWidthPercent(20f));
		table.addCell(new Cell().add(performanceExport.getTest_data1()));

		return table;
	}

	private com.itextpdf.layout.element.List createTestMethods () {
		com.itextpdf.layout.element.List sumList = new com.itextpdf.layout.element.List();

		ListItem loginItem = new ListItem("Login");
		ListItem createItem = new ListItem("Create Issue");
		ListItem searchItem = new ListItem("Search Issue");
		ListItem editItem = new ListItem("Edit Issue");
		com.itextpdf.layout.element.List listLogin = new com.itextpdf.layout.element.List(ListNumberingType.ZAPF_DINGBATS_1);
		listLogin.add("Go to Login website");
		listLogin.add("Input values and click login button");
		loginItem.add(listLogin.setMarginLeft(10f));
		com.itextpdf.layout.element.List listCreate = new com.itextpdf.layout.element.List(ListNumberingType.ZAPF_DINGBATS_1);
		listCreate.add("After Login, use quick create issue button and input the request values and click create");
		createItem.add(listCreate.setMarginLeft(10f));
		com.itextpdf.layout.element.List listSearch = new com.itextpdf.layout.element.List(ListNumberingType.ZAPF_DINGBATS_1);
		listSearch.add("After Login, input issue key and click search button in the search bar");
		searchItem.add(listSearch.setMarginLeft(10f));
		com.itextpdf.layout.element.List listEdit = new com.itextpdf.layout.element.List(ListNumberingType.ZAPF_DINGBATS_1);
		listEdit.add("View Issue: Browse an issue in issue navigator and open it/ Browse an issue in project navigator");
		listEdit.add("Add Comment: Click “Comment” button to add a comment");
		listEdit.add("Edit Issue: Click “Edit” button to edit some values and update it");
		editItem.add(listEdit.setMarginLeft(10f));

		sumList.add(loginItem);
		sumList.add(createItem);
		sumList.add(searchItem);
		sumList.add(editItem);

		return sumList;
	}
	
	private com.itextpdf.layout.element.List createScenario() {
		com.itextpdf.layout.element.List sumList = new com.itextpdf.layout.element.List();
		ListItem item = new ListItem("Details user assign as follow:");
		com.itextpdf.layout.element.List itemList = new com.itextpdf.layout.element.List();
		itemList.setListSymbol("\u2022 ");
		itemList.add("Login and do nothing 1040 users");
		itemList.add("Login and Create issue 78 users");
		itemList.add("Login and Edit issue 130 users");
		itemList.add("Login and Search issue 52 users");
		item.add(itemList);
		sumList.add(item);

		return sumList;
	}

	private void checkPerExport(PerformanceExport performanceExport) {
		if ("".equals(performanceExport.getReporter1()) || null == performanceExport.getReporter1()) {
			performanceExport.setReporter1(" - ");
		}
		if ("".equals(performanceExport.getBackground1()) || null == performanceExport.getBackground1()) {
			performanceExport.setBackground1(" - ");
		}
		if ("".equals(performanceExport.getPurpose1()) || null == performanceExport.getPurpose1()) {
			performanceExport.setPurpose1(" - ");
		}
		if ("".equals(performanceExport.getTest_server1()) || null == performanceExport.getTest_server1()) {
			performanceExport.setTest_server1(" - ");
		}
		if ("".equals(performanceExport.getTest_port1()) || null == performanceExport.getTest_port1()) {
			performanceExport.setTest_port1(" - ");
		}
		if ("".equals(performanceExport.getTest_network1()) || null == performanceExport.getTest_network1()) {
			performanceExport.setTest_network1(" - ");
		}
		if ("".equals(performanceExport.getTest_tool1()) || null == performanceExport.getTest_tool1()) {
			performanceExport.setTest_tool1(" - ");
		}
		if ("".equals(performanceExport.getTest_target1()) || null == performanceExport.getTest_target1()) {
			performanceExport.setTest_target1(" - ");
		}
		if ("".equals(performanceExport.getTest_data1()) || null == performanceExport.getTest_data1()) {
			performanceExport.setTest_data1(" - ");
		}
		if ("".equals(performanceExport.getTester_start1()) || null == performanceExport.getTester_start1()) {
			performanceExport.setTester_start1(" Null ");
		}
		if ("".equals(performanceExport.getTester_end1()) || null == performanceExport.getTester_end1()) {
			performanceExport.setTester_end1(" Null ");
		}
		if ("".equals(performanceExport.getTester_conclusion1()) || null == performanceExport.getTester_conclusion1()) {
			performanceExport.setTester_conclusion1(" - ");
		}
		if ("".equals(performanceExport.getTester_suggestion1()) || null == performanceExport.getTester_suggestion1()) {
			performanceExport.setTester_suggestion1(" - ");
		}
	}

	protected class createFooterHeader implements IEventHandler {
		protected String header;

		public void setHeader(String header) {
			this.header = header;
		}

		@Override
		public void handleEvent(Event event) {
			PdfDocumentEvent documentEvent = (PdfDocumentEvent) event;
			try {
				new PdfCanvas(documentEvent.getPage())
					.beginText()
					.setFontAndSize(PdfFontFactory.createFont(FontConstants.HELVETICA), 7)
					.moveText(250,10).showText(" All copyrights saved by ©Nokia ")
					.endText().stroke();
				new PdfCanvas(documentEvent.getPage())
					.beginText()
					.setFontAndSize(PdfFontFactory.createFont(FontConstants.HELVETICA), 7)
					.moveText(500, 830).showText(" Reporter: ".concat(header))
					.endText().stroke();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
}
